### ISSUE TITLE
ANPR

### ISSUE THREAD

**Issue by rutujar** [freelifedev/ANPR#1]
how to run this program and python scripts?

**Comment by freelifedev** [comment]
Hello, I am sorry so late.

1. Train
python train_advanced.py --samples output/examples --char-classifier output/adv_char.cpickle \
	--digit-classifier output/adv_digit.cpickle

2. Recongnize

python recognize.py --images ../testing_lp_dataset --char-classifier output/adv_char.cpickle \
	--digit-classifier output/adv_digit.cpickle

FYI > This is from https://gurus.pyimagesearch.com/lessons/improving-our-license-plate-classifier/
         But it's not free.

**Comment by rutujar** [comment]
Its Fine,i am happy that u replied to the issue @freelifedev .
can u upload the 
* char.cpickle
* digit.cpickle

what about gather_examples.py?

can i know what is the limitations of your project.
as i am doing for multiple number plate recognition it would be helpful if u can say, so that i will resolve it.

**Comment by rutujar** [comment]
What about fonts??

**Comment by freelifedev** [comment]
Dear Rutuja Rajesh.,

let me attach the files.


Sincerely,
Sunggu Kim.



2019년 3월 25일 (월) 오후 9:46, Rutuja Rajesh <notifications@github.com>님이 작성:

**Comment by rutujar** [comment]
how to install cpickle? for my ubuntu 16.04 @freelifedev

**Comment by freelifedev** [comment]
Dear Rutuja Rajesh.,

Let me share this full source code.
But do not release it on the internet , please.
Because it has copyright for pysearchimage.com which is really greate guru.
I suggest to you that have a look at the site. (
https://www.pyimagesearch.com/ )

I hope this solve your problem.

Sincery,
Sunggu Kim.


2019년 3월 27일 (수) 오전 8:17, Sung Gu Kim <kisatsg@gmail.com>님이 작성:

**Comment by rutujar** [comment]
email id: rutujarajesh23@gmail.com
